<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
  
  
  <joint name="kinetic_joint" type="fixed">
    <origin xyz="${tamanho_x/2} 0 0" rpy="0.0 0.0 0.0"/>
    <parent link="corpo_link"/>
    <child link="kinetic_link"/>
  </joint>

  <link name="kinetic_link">
    <visual>
      <material name="white"/>
      <origin xyz="0.0 0.0 0.0" rpy="${pi} 0.0 0.0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </visual>
  </link>



  <joint name="dumb_kinetic_joint" type="fixed">
        <parent link="kinetic_link"/>
        <child link="dumb_kinetic"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>


  <link name="dumb_kinetic">
    
  </link>
  
  <gazebo reference='kinetic_link'>
    <material>Gazebo/White</material>
    <sensor name="camera" type="depth">
      <update_rate>10</update_rate>
      <camera>
        <horizontal_fov>1.047198</horizontal_fov>
        <image>
          <width>640</width>
          <height>480</height>
          <!-- <format>R8G8B8</format> -->
          <format>B8G8R8</format>
        </image>
        <clip>
          <near>0.05</near>
          <far>3</far>
        </clip>
      </camera>
      <plugin name="camera_plugin" filename="libgazebo_ros_openni_kinect.so">
          <baseline>0.2</baseline>
          <alwaysOn>true</alwaysOn>
          <!-- Keep this zero, update_rate in the parent <sensor> tag
            will control the frame rate. -->
          <updateRate>0.0</updateRate>
          <cameraName>camera_ir</cameraName>
          <imageTopicName>/agent/camera/color/image_raw</imageTopicName>
          <cameraInfoTopicName>/agent/camera/color/camera_info</cameraInfoTopicName>
          <depthImageTopicName>/agent/camera/depth/image_raw</depthImageTopicName>
          <depthImageCameraInfoTopicName>/agent/camera/depth/camera_info</depthImageCameraInfoTopicName>
          <pointCloudTopicName>/agent/camera/depth/points</pointCloudTopicName>
          <frameName>dumb_kinetic</frameName>
          <pointCloudCutoff>0.5</pointCloudCutoff>
          <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
          <distortionK1>0</distortionK1>
          <distortionK2>0</distortionK2>
          <distortionK3>0</distortionK3>
          <distortionT1>0</distortionT1>
          <distortionT2>0</distortionT2>
          <CxPrime>0</CxPrime>
          <Cx>0</Cx>
          <Cy>0</Cy>
          <focalLength>0</focalLength>
          <hackBaseline>0</hackBaseline>
      </plugin>
    </sensor>
  </gazebo>
</robot>