<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="laser_joint" type="fixed">
        <parent link="corpo_link"/>
        <child link="laser_frame"/>
        <origin xyz="0 0 ${tamanho_z/2+0.01}" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="laser_frame">
        <material>Gazebo/White</material>

        <sensor name="laser" type="ray">
            <pose>0 0 0 0 1.57079633 0</pose>
            <ray>
                <scan>
                  <horizontal>
                      <samples>360</samples>
                      <resolution>1</resolution>
                      <min_angle>-${pi}</min_angle>
                      <max_angle>${pi}</max_angle>
                  </horizontal>
                </scan>
                <range>
                  <min>0.06</min> <!-- do not change: use min_distance (below) for realistic behavior (smaller values cause issues) -->
                  <max>10</max>   <!-- do not change: use min_distance (below) for realistic behavior (bigger values cause issues) -->
                </range>
            </ray>
            <plugin name="laser_gazebo" filename="libgazebo_ros_laser.so">
                <topicName>/scan</topicName>
                <frameName>laser_frame</frameName>
            </plugin>
            <update_rate>10</update_rate>
            <visualize>false</visualize>
        </sensor>
    </gazebo>

</robot>
