<?xml version="1.0"?>
<robot name="carro_mengao" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="inercia.xacro"/>

  <xacro:property name="tamanho_x" value="0.20" />
  <xacro:property name="tamanho_y" value="0.30" />
  <xacro:property name="tamanho_z" value="0.15" />

  <material name="blue">
    <color rgba="0 0 1 1"/>
  </material>

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>


  <!-- base link -->
  <link name="base_link">
    
  </link>

  <!-- corpo -->

  <joint name="corpo_joint" type="fixed">
    <origin xyz="-${tamanho_x/2} 0.0 0.0" rpy="0.0 0.0 0.0"/>
    <parent link="base_link"/>
    <child link="corpo_link"/>
  </joint>
  
  <link name="corpo_link">
      <visual>
        <geometry>
            <box size="${tamanho_x} ${tamanho_y} ${tamanho_z}"/>
        </geometry>
        <material name="red"/>
      </visual>
      <collision>
        <geometry>
            <box size="${tamanho_x} ${tamanho_y} ${tamanho_z}"/>
        </geometry>
      </collision>
      <xacro:inertial_box mass = "0.5" x="${tamanho_x}" y="${tamanho_y}" z="${tamanho_z}" >
        <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      </xacro:inertial_box>
  </link>

  <gazebo reference="corpo_link">
    <material>Gazebo/Red</material>
  </gazebo>


  <!-- roda esquerda -->
  <joint name="debug_joint" type="fixed">
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    <parent link="roda_esquerda_link"/>
    <child link="debug_box"/>
  </joint>

  <link name="debug_box">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>


  <joint name="roda_esquerda_joint" type="continuous">
    
    <parent link="base_link"/>
    
    <child link="roda_esquerda_link"/>
    
    <origin xyz="-${tamanho_x/2+0.05} ${tamanho_y/2} -${tamanho_z/2}" rpy="-${pi/2} 0.0 0.0"/>
    
    <axis xyz="0.0 0.0 1.0"/>
  
  </joint>

  <link name="roda_esquerda_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.01" radius="0.05" length="0.04">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="roda_esquerda_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <!-- roda direita -->
  <joint name="debug_direita_joint" type="fixed">
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    <parent link="roda_direita_link"/>
    <child link="debug_box_2"/>
  </joint>

  <link name="debug_box_2">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="roda_direita_joint" type="continuous">
    
    <parent link="base_link"/>
    
    <child link="roda_direita_link"/>
    
    <origin xyz="-${tamanho_x/2+0.05} -${tamanho_y/2} -${tamanho_z/2}" rpy="${pi/2} 0.0 0.0"/>

    <axis xyz="0.0 0.0 -1.0"/>
  </joint>

  <link name="roda_direita_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.04"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.01" radius="0.05" length="0.04">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:inertial_cylinder>
  </link>

  <gazebo reference="roda_direita_link">
    <material>Gazebo/Blue</material>
  </gazebo>


  <!-- bolinha -->
  <joint name="bolinha_joint" type="fixed">
    <origin xyz="-0.05 0.0 -${tamanho_z/2}" rpy="0.0 0.0 0.0"/>
    <parent link="base_link"/>
    <child link="bolinha_link"/>
  </joint>


  <link name="bolinha_link">
    <visual>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
    <xacro:inertial_sphere mass="0.01" radius="0.05">
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </xacro:inertial_sphere>

  </link>

  <gazebo reference="bolinha_link">
    <material>Gazebo/Black</material>
    <mu1 value="0.001"/>
    <mu2 value="0.001"/>
  </gazebo>



</robot>